## Implementation of Matrix Product

### Problem 1: Matrix product by hand

<img src="problem_1.png">

### Problem 2: Calculation by NumPy function

In [18]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

ab_ndarray = np.matmul(a_ndarray,b_ndarray)

ab_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

### Problem 3: Implementation of calculation of a certain element

In [19]:
result = 0
for k in range(3):
    result += a_ndarray[0, k] * b_ndarray[k, 0]

print(result)


6


### Problem 4: Creating a function that performs matrix multiplication

In [20]:
from typing import Any
from numpy import ndarray, dtype


def compute_product(a: ndarray[Any, dtype], b: ndarray[Any, dtype]):
    _ab_ndarray = np.empty([3, 3])
    for row in range(a.shape[0]):
        for column in range(b.shape[1]):
            _ab_ndarray[row][column] = sum(a[row, :] * b[:, column])
    return _ab_ndarray

compute_product(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

### Problem 5: Judge the input whose calculation is not defined

In [21]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

if d_ndarray.shape[1] != e_ndarray.shape[0]:
    print("Error: The number of columns in matrix D must equal the number of rows in matrix E.")
else:
    compute_product(d_ndarray, e_ndarray)

Error: The number of columns in matrix D must equal the number of rows in matrix E.


### Problem 6: Transposition

In [28]:
ab_ndarray_transposed = np.transpose(compute_product(a_ndarray, b_ndarray))
ab_ndarray_transposed

array([[  6.,  12., -18.],
       [ 29.,  52., -51.],
       [-20.,  38., -48.]])