## Implementation of Matrix Product

### Problem 1: Matrix product by hand

In [72]:
import numpy as np
from numpy import ndarray

a_ndarray = np.array([[-1, 2, 3], 
                      [4, -5, 6], 
                      [7,  8, 9]])

b_ndarray = np.array([[0, 2,  1], 
                      [0, 2, -8], 
                      [2, 9, -1]])

def multiply_matrices(_matrix1: ndarray, _matrix2: ndarray) -> ndarray:
    _result = np.array([])
    for i in range(len(_matrix1)):
        for j in range(len(_matrix2[0])):
            cell_result = 0
            for k in range(len(_matrix2)):
                cell_result += _matrix1[i][k] * _matrix2[k][j]
            _result = np.append(_result, cell_result)
    return _result.reshape(_matrix1.shape)

print(multiply_matrices(a_ndarray, b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [ 18. 111. -66.]]
