## Implementation of Matrix Product

### Problem 1: Matrix product by hand

In [70]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], 
                      [4, -5, 6], 
                      [7,  8, 9]])

b_ndarray = np.array([[0, 2,  1], 
                      [0, 2, -8], 
                      [2, 9, -1]])

# a_ndarray = np.array([['a', 'b', 'c'], 
#                       ['d', 'e', 'f'], 
#                       ['g', 'h', 'i']])
# 
# b_ndarray = np.array([['j', 'k', 'l'], 
#                       ['m', 'n', 'o'], 
#                       ['p', 'k', 'r']])

result = np.array([])

aux: np.ndarray = np.array([])
for i in range(len(a_ndarray)):
    for j in range(len(b_ndarray[0])):
        cell_result = 0
        for k in range(len(b_ndarray)):
            # aux = np.append(aux, a_ndarray[i][k] * b_ndarray[k][j])
            # cell_result += f"{a_ndarray[i][k]}{b_ndarray[k][j]} "
            cell_result += a_ndarray[i][k] * b_ndarray[k][j]
            # print(f"{a_ndarray[i][k]} * {b_ndarray[k][j]}")
            # result = np.append(result, cell_result)
        # print(cell_result)
        # aux = np.append(aux, cell_result)
        result = np.append(result, cell_result)
        # aux = np.array([])
    # print(aux)
    # print("==========")
print(result.reshape((3, 3)))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [ 18. 111. -66.]]
